// Generated by: node --import tsx scripts/generate-voted-resolved-fixtures.ts
// Do not edit by hand.

import type { VotedCardProps } from '../../types/votedCard.js';

export const votedResolvedFixtures = {
  "sandersSjres3Nay": {
    "nameTitle": "Sen. Bernard Sanders (VT)",
    "party": "Independent",
    "stateName": "Vermont",
    "chamber": "sen",
    "state": "VT",
    "imageUrl": "/images/legislators/S000033.jpg",
    "voteCast": "Nay",
    "voteTitle": "On the Joint Resolution S.J.Res. 3",
    "legislationIdentifier": "S.J. Res. 3",
    "legislationType": "joint resolution",
    "billTitle": "Disapproval of IRS rule on the Gross Proceeds Reporting by Brokers That Regularly Provide Services Effectuating Digital Asset Sales",
    "displayName": "Sen. Bernard Sanders",
    "memberSubtitle": "Independent, Vermont Senator",
    "voteVerb": "voted",
    "emoji": "👎",
    "actionLabel": "Nay"
  }
} as const satisfies Record<string, VotedCardProps>;
