/**
 * Regenerates {@link votedResolvedFixtures} from on-disk bill/legislator JSON.
 * Run: `node --import tsx scripts/generate-voted-resolved-fixtures.ts`
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEFAULT_REAL_VOTE } from '../src/components/social-cards/votedRealVoteDefaults.js';
import { toVotedCardProps } from '../src/utils/legislatorVoteView.js';
import { resolveLegislatorVoteViewFromFiles } from '../src/utils/resolveLegislatorVoteViewFromFiles.js';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'src/components/social-cards/votedResolvedFixtures.ts');

const result = await resolveLegislatorVoteViewFromFiles(DEFAULT_REAL_VOTE);
if (!result.ok) {
  throw new Error(`Fixture generation failed: ${result.reason}`);
}

const props = toVotedCardProps(result.view);
const fixtures = { sandersSjres3Nay: props };

const content = `// Generated by: node --import tsx scripts/generate-voted-resolved-fixtures.ts
// Do not edit by hand.

import type { VotedCardProps } from '../../types/votedCard.js';

export const votedResolvedFixtures = ${JSON.stringify(fixtures, null, 2)} as const satisfies Record<string, VotedCardProps>;
`;

writeFileSync(OUT, content);
console.log(`Wrote ${OUT}`);
