// Generated by ts-to-zod
import { z } from "astro/zod";

export const congressApiRequestSchema = z.object({
    congress: z.string().optional(),
    contentType: z.string(),
    format: z.string(),
    session: z.string().optional()
});

export const congressApiPaginationSchema = z.object({
    count: z.number(),
    next: z.string().optional(),
    prev: z.string().optional()
});

export const congressApiParamsSchema = z.object({
    format: z.union([z.literal("xml"), z.literal("json")]).optional()
});

export const congressApiParamsListSchema = congressApiParamsSchema.and(z.object({
    offset: z.number().optional(),
    limit: z.number().optional()
}));

export const memberListParamsSchema = congressApiParamsListSchema.and(z.object({
    currentMember: z.boolean().optional(),
    fromDateTime: z.string().optional(),
    toDateTime: z.string().optional()
}));

export const houseVoteListParamsSchema = congressApiParamsListSchema;

export const billListParamsSchema = congressApiParamsListSchema.and(z.object({
    fromDateTime: z.string().optional(),
    toDateTime: z.string().optional()
}));

export const billActionsParamsSchema = congressApiParamsListSchema;

export const sponsoredLegislationParamsSchema = congressApiParamsListSchema;

export const cosponsoredLegislationParamsSchema = congressApiParamsListSchema;

export const committeeListParamsSchema = congressApiParamsListSchema;

export const nominationListParamsSchema = congressApiParamsListSchema;

export const partyHistorySchema = z.object({
    partyAbbreviation: z.string(),
    partyName: z.string(),
    startYear: z.number()
});

export const leadershipSchema = z.object({
    congress: z.number().optional(),
    current: z.boolean().optional(),
    type: z.string().optional()
});

export const previousNameSchema = z.object({
    directOrderName: z.string(),
    endDate: z.string().optional(),
    firstName: z.string(),
    honorificName: z.string(),
    invertedOrderName: z.string(),
    lastName: z.string(),
    startDate: z.string()
});

export const addressInformationSchema = z.object({
    city: z.string(),
    district: z.string(),
    officeAddress: z.string(),
    phoneNumber: z.string(),
    zipCode: z.number()
});

export const depictionSchema = z.object({
    attribution: z.string().optional(),
    imageUrl: z.string()
});

export const legislationReferenceSchema = z.object({
    count: z.number(),
    url: z.string()
});

export const memberTermSchema = z.object({
    chamber: z.string(),
    congress: z.number(),
    district: z.number().optional(),
    endYear: z.number(),
    memberType: z.string(),
    startYear: z.number(),
    stateCode: z.string(),
    stateName: z.string()
});

export const memberInfoSchema = z.object({
    addressInformation: addressInformationSchema.optional(),
    bioguideId: z.string(),
    birthYear: z.string().optional(),
    cosponsoredLegislation: legislationReferenceSchema.optional(),
    currentMember: z.boolean(),
    depiction: depictionSchema.optional(),
    directOrderName: z.string(),
    district: z.number().optional(),
    firstName: z.string(),
    honorificName: z.string(),
    invertedOrderName: z.string(),
    lastName: z.string(),
    leadership: z.array(leadershipSchema).optional(),
    middleName: z.string().optional(),
    nickName: z.string().optional(),
    officialWebsiteUrl: z.string().optional(),
    party: z.string(),
    partyHistory: z.array(partyHistorySchema),
    previousNames: z.array(previousNameSchema).optional(),
    sponsoredLegislation: legislationReferenceSchema.optional(),
    state: z.string(),
    terms: z.array(memberTermSchema),
    updateDate: z.string(),
    url: z.string()
});

export const committeeInfoSchema = z.object({
    chamber: z.string(),
    name: z.string(),
    systemCode: z.string(),
    type: z.string(),
    url: z.string(),
    updateDate: z.string()
});

export const nominationInfoSchema = z.object({
    congress: z.number(),
    description: z.string(),
    latestAction: z.object({
        actionDate: z.string(),
        text: z.string()
    }).optional(),
    nominationNumber: z.string(),
    partNumber: z.string(),
    receivedDate: z.string(),
    url: z.string(),
    updateDate: z.string()
});

export const houseVotePartySchema = z.object({
    name: z.string().optional(),
    type: z.string().optional()
});

export const houseVotePartyTotalSchema = z.object({
    party: houseVotePartySchema.optional(),
    voteParty: z.string().optional(),
    yeaTotal: z.number().optional(),
    nayTotal: z.number().optional(),
    presentTotal: z.number().optional(),
    notVotingTotal: z.number().optional()
});

export const houseRollCallVoteSchema = z.object({
    congress: z.number(),
    identifier: z.number(),
    legislationNumber: z.string().optional(),
    legislationType: z.string().optional(),
    legislationUrl: z.string().optional(),
    result: z.string(),
    rollCallNumber: z.number(),
    sessionNumber: z.number(),
    sourceDataURL: z.string(),
    startDate: z.string(),
    updateDate: z.string(),
    url: z.string(),
    voteType: z.string()
});

export const houseRollCallVoteDetailsSchema = z.object({
    congress: z.number(),
    identifier: z.number(),
    sessionNumber: z.number(),
    rollCallNumber: z.number(),
    startDate: z.string(),
    updateDate: z.string(),
    voteQuestion: z.string(),
    voteType: z.string(),
    result: z.string(),
    sourceDataURL: z.string(),
    legislationType: z.string().optional(),
    legislationNumber: z.string().optional(),
    legislationUrl: z.string().optional(),
    votePartyTotal: z.array(houseVotePartyTotalSchema)
});

export const houseVoteMemberSchema = z.object({
    bioguideID: z.string(),
    firstName: z.string(),
    lastName: z.string(),
    voteCast: z.string(),
    voteParty: z.string(),
    voteState: z.string()
});

export const houseVoteMemberVotesSchema = z.object({
    congress: z.number(),
    identifier: z.number(),
    legislationNumber: z.string(),
    legislationType: z.string(),
    legislationUrl: z.string(),
    result: z.string(),
    results: z.array(houseVoteMemberSchema),
    rollCallNumber: z.number(),
    sessionNumber: z.number(),
    sourceDataURL: z.string(),
    startDate: z.string(),
    updateDate: z.string(),
    voteQuestion: z.string(),
    voteType: z.string()
});

export const senateVoteSchema = z.object({
    congress: z.number(),
    date: z.string(),
    issue: z.string(),
    question: z.string(),
    result: z.string(),
    title: z.string(),
    vote_number: z.number(),
    vote_tally: z.object({
        yeas: z.number(),
        nays: z.number(),
        present: z.number(),
        absent: z.number()
    }).optional(),
    vote_document_text: z.string().optional(),
    vote_document_url: z.string().optional()
});

export const senateVoteMemberSchema = z.object({
    bioguide_id: z.string(),
    first_name: z.string(),
    last_name: z.string(),
    party: z.string(),
    state: z.string(),
    vote_cast: z.string()
});

export const senateVoteDetailsSchema = z.object({
    congress: z.number(),
    date: z.string(),
    issue: z.string(),
    question: z.string(),
    result: z.string(),
    title: z.string(),
    vote_number: z.number(),
    members: z.array(senateVoteMemberSchema),
    vote_tally: z.object({
        yeas: z.number(),
        nays: z.number(),
        present: z.number(),
        absent: z.number()
    })
});

export const recordedVoteSchema = z.object({
    id: z.string().optional(),
    chamber: z.string(),
    congress: z.number(),
    date: z.string(),
    rollNumber: z.number(),
    sessionNumber: z.number(),
    url: z.string()
});

export const billActionSchema = z.object({
    actionCode: z.string().optional(),
    actionDate: z.string(),
    text: z.string(),
    type: z.string().optional(),
    actionTime: z.string().optional(),
    committees: z.array(z.object({
        name: z.string(),
        systemCode: z.string(),
        url: z.string()
    })).optional(),
    recordedVotes: z.array(recordedVoteSchema).optional(),
    sourceSystem: z.object({
        code: z.union([z.string(), z.number()]).optional(),
        name: z.string()
    }).optional()
});

export const billLatestActionSchema = z.object({
    actionDate: z.string(),
    actionTime: z.string().optional(),
    text: z.string(),
    actionCode: z.string().optional()
});

export const billSubjectSchema = z.object({
    name: z.string(),
    updateDate: z.string().optional()
});

export const billPolicyAreaSchema = z.object({
    name: z.string(),
    updateDate: z.string().optional()
});

export const billSponsorSchema = z.object({
    bioguideId: z.string(),
    district: z.number().optional(),
    firstName: z.string(),
    fullName: z.string(),
    lastName: z.string(),
    middleName: z.string().optional(),
    party: z.string(),
    state: z.string(),
    url: z.string()
});

export const billCosponsorSchema = z.object({
    bioguideId: z.string(),
    district: z.number().optional(),
    firstName: z.string(),
    fullName: z.string(),
    lastName: z.string(),
    middleName: z.string().optional(),
    party: z.string(),
    sponsorshipDate: z.string(),
    sponsorshipWithdrawnDate: z.string().optional(),
    state: z.string(),
    url: z.string()
});

export const billCommitteeSchema = z.object({
    name: z.string(),
    systemCode: z.string(),
    url: z.string(),
    activities: z.array(z.object({
        date: z.string(),
        name: z.string()
    })).optional(),
    subcommittees: z.array(z.object({
        name: z.string(),
        systemCode: z.string(),
        url: z.string(),
        activities: z.array(z.object({
            date: z.string(),
            name: z.string()
        })).optional()
    })).optional()
});

export const billRelatedBillSchema = z.object({
    congress: z.number(),
    latestAction: billLatestActionSchema.optional(),
    number: z.string(),
    relationshipDetails: z.array(z.object({
        identifiedBy: z.string(),
        type: z.string()
    })).optional(),
    title: z.string(),
    type: z.string(),
    url: z.string()
});

export const billAmendmentSchema = z.object({
    congress: z.number(),
    latestAction: billLatestActionSchema.optional(),
    number: z.string(),
    purpose: z.string(),
    type: z.string(),
    url: z.string()
});

export const billTypesSchema = z.union([z.literal("hr"), z.literal("s"), z.literal("hjres"), z.literal("sjres"), z.literal("hconres"), z.literal("sconres"), z.literal("hres"), z.literal("sres"), z.literal("HR"), z.literal("S"), z.literal("HJRES"), z.literal("SJRES"), z.literal("HCONRES"), z.literal("SCONRES"), z.literal("HRES"), z.literal("SRES")]);

export const chambersSchema = z.union([z.literal("house"), z.literal("senate"), z.literal("House"), z.literal("Senate")]);

export const chamberCodesSchema = z.union([z.literal("h"), z.literal("s"), z.literal("H"), z.literal("S")]);

export const baseBillSummarySchema = z.object({
    congress: z.number(),
    number: z.string(),
    type: billTypesSchema,
    title: z.string(),
    summary: z.string().optional(),
    latestAction: billLatestActionSchema.optional(),
    originChamber: chambersSchema,
    originChamberCode: chamberCodesSchema,
    url: z.string().optional(),
    introducedDate: z.string().optional(),
    updateDate: z.string().optional()
});

export const billActionSummarySchema = z.object({
    count: z.number().optional(),
    url: z.string().optional()
});

export const extendedBillSummarySchema = baseBillSummarySchema.and(z.object({
    constitutionalAuthorityStatementText: z.string().optional(),
    policyArea: billPolicyAreaSchema.optional(),
    subjects: billSubjectSchema.optional(),
    sponsors: billSponsorSchema.optional(),
    actions: billActionSummarySchema.optional(),
    cosponsors: billCosponsorSchema.optional(),
    committees: billCommitteeSchema.optional(),
    committeeReports: z.array(z.object({
        citation: z.string(),
        url: z.string()
    })).optional(),
    relatedBills: billRelatedBillSchema.optional(),
    amendments: billAmendmentSchema.optional(),
    cboCostEstimates: z.array(z.object({
        description: z.string(),
        pubDate: z.string(),
        title: z.string(),
        url: z.string()
    })).optional(),
    laws: z.array(z.object({
        number: z.string(),
        type: z.string()
    })).optional(),
    notes: z.array(z.object({
        text: z.string()
    })).optional(),
    textVersions: z.array(z.object({
        date: z.string(),
        type: z.string(),
        formats: z.array(z.object({
            type: z.string(),
            url: z.string()
        }))
    })).optional()
}));

export const houseVoteListResponseSchema = z.object({
    houseRollCallVotes: z.array(houseRollCallVoteSchema),
    pagination: congressApiPaginationSchema,
    request: congressApiRequestSchema
});

export const houseVoteResponseSchema = z.object({
    houseRollCallVote: houseRollCallVoteDetailsSchema,
    request: congressApiRequestSchema
});

export const houseMembersResponseSchema = z.object({
    houseRollCallVoteMemberVotes: houseVoteMemberVotesSchema,
    request: congressApiRequestSchema
});

export const senateVoteListResponseSchema = z.object({
    votes: z.array(senateVoteSchema),
    pagination: congressApiPaginationSchema,
    request: congressApiRequestSchema
});

export const billResponseSchema = z.object({
    bill: extendedBillSummarySchema,
    request: congressApiRequestSchema.optional()
});

export const billActionsResponseSchema = z.object({
    actions: z.array(billActionSchema),
    pagination: congressApiPaginationSchema.optional(),
    request: congressApiRequestSchema.optional()
});

export const billListResponseSchema = z.object({
    bills: z.array(baseBillSummarySchema),
    pagination: congressApiPaginationSchema,
    request: congressApiRequestSchema
});

export const memberResponseSchema = z.object({
    member: memberInfoSchema,
    request: congressApiRequestSchema.optional()
});

export const memberListInfoSchema = z.object({
    bioguideId: z.string(),
    depiction: z.object({
        imageUrl: z.string()
    }).optional(),
    district: z.number().optional(),
    name: z.string(),
    partyName: z.string(),
    state: z.string(),
    terms: z.array(z.object({
        item: z.number()
    })),
    updateDate: z.string(),
    url: z.string()
});

export const memberListResponseSchema = z.object({
    members: z.array(memberListInfoSchema),
    pagination: congressApiPaginationSchema,
    request: congressApiRequestSchema
});

export const sponsoredLegislationItemSchema = z.object({
    congress: z.number(),
    latestAction: billLatestActionSchema.optional(),
    number: z.string(),
    policyArea: z.object({
        name: z.string()
    }).optional(),
    title: z.string(),
    type: z.string(),
    url: z.string(),
    introducedDate: z.string().optional(),
    updateDate: z.string().optional()
});

export const sponsoredLegislationResponseSchema = z.object({
    sponsoredLegislation: z.array(sponsoredLegislationItemSchema),
    pagination: congressApiPaginationSchema,
    request: congressApiRequestSchema
});

export const cosponsoredLegislationItemSchema = z.object({
    congress: z.number(),
    latestAction: billLatestActionSchema.optional(),
    number: z.string(),
    policyArea: z.object({
        name: z.string()
    }).optional(),
    title: z.string(),
    type: z.string(),
    url: z.string(),
    cosponsorshipDate: z.string().optional(),
    cosponsorshipWithdrawnDate: z.string().optional(),
    updateDate: z.string().optional()
});

export const cosponsoredLegislationResponseSchema = z.object({
    cosponsoredLegislation: z.array(cosponsoredLegislationItemSchema),
    pagination: congressApiPaginationSchema,
    request: congressApiRequestSchema
});

export const committeeListResponseSchema = z.object({
    committees: z.array(committeeInfoSchema),
    pagination: congressApiPaginationSchema,
    request: congressApiRequestSchema
});

export const nominationListResponseSchema = z.object({
    nominations: z.array(nominationInfoSchema),
    pagination: congressApiPaginationSchema,
    request: congressApiRequestSchema
});

export const congressApiErrorSchema = z.object({
    error: z.string(),
    message: z.string().optional(),
    request: z.record(z.string(), z.string()).optional()
});

export const rawLegislatorBioSchema = z.object({
    birthday: z.string().optional(),
    gender: z.string().optional(),
    religion: z.string().optional()
});

export const rawLegislatorIdSchema = z.object({
    bioguide: z.string(),
    thomas: z.string().optional(),
    lis: z.string().optional(),
    govtrack: z.number().optional(),
    opensecrets: z.string().optional(),
    votesmart: z.number().optional(),
    fec: z.array(z.string()).optional(),
    cspan: z.number().optional(),
    wikipedia: z.string().optional(),
    house_history: z.number().optional(),
    ballotpedia: z.string().optional(),
    maplight: z.number().optional(),
    icpsr: z.number().optional(),
    wikidata: z.string().optional(),
    google_entity_id: z.string().optional(),
    pictorial: z.number().optional()
});

export const rawLegislatorNameSchema = z.object({
    first: z.string(),
    last: z.string(),
    official_full: z.string().optional(),
    nickname: z.string().optional(),
    middle: z.string().optional(),
    suffix: z.string().optional()
});

export const rawLegislatorTermSchema = z.object({
    type: z.string(),
    start: z.string(),
    end: z.string(),
    state: z.string(),
    district: z.number().optional(),
    party: z.string(),
    class: z.number().optional(),
    state_rank: z.string().optional(),
    url: z.string().optional(),
    address: z.string().optional(),
    office: z.string().optional(),
    phone: z.string().optional(),
    fax: z.string().optional(),
    contact_form: z.string().optional(),
    rss_url: z.string().optional(),
    how: z.string().optional()
});

export const rawLegislatorSocialSchema = z.object({
    twitter: z.string().optional(),
    facebook: z.string().optional(),
    youtube: z.string().optional(),
    instagram: z.string().optional(),
    youtube_id: z.string().optional(),
    instagram_id: z.string().optional(),
    twitter_id: z.string().optional(),
    facebook_id: z.string().optional()
});

export const rawLegislatorSocialMediaSchema = z.object({
    id: z.object({
        bioguide: z.string(),
        thomas: z.string().optional(),
        govtrack: z.number().optional()
    }),
    social: rawLegislatorSocialSchema
});

export const rawSenateCommitteeSchema = z.object({
    _: z.string().optional(),
    $: z.object({
        code: z.string().optional()
    }).optional()
});

export const rawSenateMemberSchema = z.object({
    member_full: z.string().optional(),
    party: z.string().optional(),
    state: z.string().optional(),
    address: z.string().optional(),
    bioguide_id: z.string().optional(),
    office: z.string().optional(),
    phone: z.string().optional(),
    lis_member_id: z.string().optional(),
    committees: z.object({
        committee: z.union([rawSenateCommitteeSchema, z.array(rawSenateCommitteeSchema)]).optional()
    }).optional()
});

export const rawLegislatorSchema = z.object({
    id: rawLegislatorIdSchema,
    name: rawLegislatorNameSchema,
    bio: rawLegislatorBioSchema,
    terms: z.array(rawLegislatorTermSchema)
});

export const rawLegislatorsSocialMediaDataSchema = z.array(rawLegislatorSocialMediaSchema);

export const legislatorBioSchema = rawLegislatorBioSchema.and(z.object({
    lis_member_id: z.string().optional(),
    address: z.string().optional(),
    office: z.string().optional(),
    phone: z.string().optional()
}));

export const legislatorIdSchema = rawLegislatorIdSchema.and(rawLegislatorSocialSchema).and(z.object({
    bioguide: z.string()
}));

export const legislatorSchema = memberInfoSchema.and(z.object({
    id: legislatorIdSchema.optional(),
    name: rawLegislatorNameSchema.optional(),
    bio: legislatorBioSchema.optional(),
    latest_term: rawLegislatorTermSchema.optional(),
    lis_member_id: z.string().optional(),
    committees: z.array(z.object({
        name: z.string().optional(),
        code: z.string().optional()
    })).optional()
}));

export const legislatorSmallSchema = z.object({
    id: z.string(),
    bioguide: z.string(),
    name: z.string().optional(),
    lastName: z.string().optional(),
    state: z.string().optional(),
    party: z.string().optional(),
    district: z.number().optional(),
    nameTitle: z.string(),
    attribution: z.string().optional(),
    imageUrl: z.string().optional(),
    stateRank: z.string().optional(),
    type: z.string().optional(),
    lis_member_id: z.string().optional()
});

export const senateRollCallVoteMemberSchema = z.object({
    member_full: z.string(),
    last_name: z.string(),
    first_name: z.string(),
    party: z.string(),
    state: z.string(),
    vote_cast: z.string(),
    lis_member_id: z.string()
});

export const senateRollCallVoteCountSchema = z.object({
    yeas: z.union([z.string(), z.number()]).optional(),
    nays: z.union([z.string(), z.number()]).optional(),
    present: z.union([z.string(), z.number()]).optional(),
    absent: z.union([z.string(), z.number()]).optional()
});

export const senateRollCallVoteXmlSchema = z.object({
    roll_call_vote: z.object({
        congress: z.string(),
        session: z.string(),
        congress_year: z.string(),
        vote_number: z.string(),
        vote_date: z.string(),
        modify_date: z.string().optional(),
        vote_question_text: z.string(),
        vote_document_text: z.string().optional(),
        vote_result_text: z.string(),
        question: z.string().optional(),
        vote_title: z.string().optional(),
        majority_requirement: z.string().optional(),
        vote_result: z.string(),
        document: z.object({
            document_congress: z.string().optional(),
            document_type: z.string().optional(),
            document_number: z.string().optional(),
            document_name: z.string().optional(),
            document_title: z.string().optional()
        }).optional(),
        amendment: z.object({
            amendment_number: z.string().optional(),
            amendment_to_document_number: z.string().optional(),
            amendment_to_amendment_number: z.string().optional()
        }).optional(),
        count: senateRollCallVoteCountSchema,
        tie_breaker: z.object({
            by_whom: z.string().optional(),
            vote_cast: z.string().optional()
        }).optional(),
        members: z.object({
            member: z.array(senateRollCallVoteMemberSchema)
        })
    })
});

export const chamberVoteSchema = z.record(z.string(), z.string());

export const billChamberVotesSchema = z.object({
    houseVotes: z.array(chamberVoteSchema).optional(),
    senateVotes: z.array(chamberVoteSchema).optional()
});

export const houseVoteDataSchema = z.object({
    votes: chamberVoteSchema,
    result: z.string(),
    votePartyTotal: z.array(houseVotePartyTotalSchema),
    voteUrl: z.string(),
    question: z.string()
});

export const senateVoteDataSchema = z.object({
    votes: chamberVoteSchema,
    result: z.string(),
    senateCount: senateRollCallVoteCountSchema,
    voteUrl: z.string(),
    question: z.string()
});

export const recordedVoteWithVotesSchema = recordedVoteSchema.and(z.object({
    voteNumber: z.number().optional(),
    votes: chamberVoteSchema.optional(),
    result: z.string().optional(),
    senateCount: senateRollCallVoteCountSchema.optional(),
    votePartyTotal: z.array(houseVotePartyTotalSchema).optional(),
    voteUrl: z.string().optional(),
    question: z.string().optional()
}));

export const billActionWithVotesSchema = billActionSchema.and(z.object({
    recordedVotes: z.array(recordedVoteWithVotesSchema).optional()
}));

export const extendedBillActionSchema = billActionSummarySchema.and(z.object({
    actions: z.array(billActionWithVotesSchema)
}));

export const billTitleSchema = z.object({
    title: z.string(),
    titleType: z.string(),
    titleTypeCode: z.union([z.number(), z.string()]).optional(),
    updateDate: z.string(),
    billTextVersionCode: z.string().optional(),
    billTextVersionName: z.string().optional(),
    chamberCode: z.string().optional(),
    chamberName: z.string().optional(),
    sourceSystem: z.object({
        code: z.union([z.number(), z.string()]).optional(),
        name: z.string().optional()
    }).optional()
});

export const billTitlesDataSchema = z.object({
    titles: z.array(billTitleSchema)
});

export const billWithActionsSchema = extendedBillSummarySchema.and(z.object({
    actions: extendedBillActionSchema,
    titles: billTitlesDataSchema.optional(),
    lastActionDate: z.string().optional(),
    lastRecordedVoteDate: z.string().optional(),
}));

export const congressApiConfigSchema = z.object({
    baseUrl: z.string(),
    apiKey: z.string(),
    format: z.union([z.literal("json"), z.literal("xml")]),
    timeout: z.number().optional()
});

export const rawSenateMemberDataSchema = z.object({
    senators: z.object({
        senator: z.array(rawSenateMemberSchema).optional()
    }).optional()
});

export const rawLegislatorsDataSchema = z.array(rawLegislatorSchema);

// ===== CHANGELOG SCHEMAS (IDs only; UI resolves from legislators/bills collections) =====

/** Bill id string, or a rich row (e.g. from newer generate-change-summary output). */
export const changelogBillRichSchema = z.object({
  id: z.string(),
  title: z.string().optional(),
  congress: z.number().optional(),
  billType: z.string().optional(),
  number: z.string().optional(),
  url: z.string().optional(),
});

export const changelogBillRefSchema = z.union([z.string(), changelogBillRichSchema]);

export type ChangelogBillRef = z.infer<typeof changelogBillRefSchema>;

export const changelogEntrySchema = z.object({
  date: z.string(),
  runId: z.string(),
  legislators: z.object({
    added: z.array(z.string()),
    updated: z.array(z.string()),
    removed: z.array(z.string()),
  }),
  bills: z.object({
    added: z.array(changelogBillRefSchema),
    updated: z.array(changelogBillRefSchema),
    newLaws: z.array(changelogBillRefSchema),
    withNewVotes: z.array(changelogBillRefSchema),
  }),
});
